"use client";

import { Brain, Zap, Trophy, Coins, Shield, Users, Sparkles, Target } from "lucide-react";

export function Features() {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered Puzzles",
      description: "Every puzzle is uniquely generated by advanced AI, ensuring infinite replayability and fresh challenges.",
      color: "from-purple-500 to-pink-500",
      borderColor: "border-purple-500/30 hover:border-purple-500/60",
    },
    {
      icon: Zap,
      title: "Dynamic Difficulty",
      description: "Adaptive AI adjusts challenge levels in real-time based on your performance and skill rating.",
      color: "from-yellow-500 to-orange-500",
      borderColor: "border-yellow-500/30 hover:border-yellow-500/60",
    },
    {
      icon: Coins,
      title: "Play-to-Earn $CRU",
      description: "Earn $CRU tokens for every level completed, puzzle solved, and achievement unlocked.",
      color: "from-green-500 to-emerald-500",
      borderColor: "border-green-500/30 hover:border-green-500/60",
    },
    {
      icon: Shield,
      title: "NFT Collectibles",
      description: "Mint unique Bristonite NFTs as proof of your achievements and trade them on OneDEX.",
      color: "from-blue-500 to-cyan-500",
      borderColor: "border-blue-500/30 hover:border-blue-500/60",
    },
    {
      icon: Trophy,
      title: "Global Leaderboard",
      description: "Compete with players worldwide on the blockchain-verified leaderboard system.",
      color: "from-red-500 to-pink-500",
      borderColor: "border-red-500/30 hover:border-red-500/60",
    },
    {
      icon: Users,
      title: "Multiplayer Modes",
      description: "Team up in co-op mode or compete in PvP battles with on-chain match recording.",
      color: "from-indigo-500 to-purple-500",
      borderColor: "border-indigo-500/30 hover:border-indigo-500/60",
    },
    {
      icon: Sparkles,
      title: "DeFi Integration",
      description: "Stake tokens, provide liquidity, and participate in yield farming for passive rewards.",
      color: "from-teal-500 to-green-500",
      borderColor: "border-teal-500/30 hover:border-teal-500/60",
    },
    {
      icon: Target,
      title: "Procedural Worlds",
      description: "Explore 4 unique temporal worlds with procedurally generated levels and hazards.",
      color: "from-orange-500 to-red-500",
      borderColor: "border-orange-500/30 hover:border-orange-500/60",
    },
  ];

  return (
    <section className="relative py-32 px-4 overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-purple-900/10 to-transparent"></div>
      
      <div className="relative z-10 max-w-7xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-20">
          <div className="inline-block mb-4">
            <div className="glass-strong px-6 py-2 rounded-full border border-purple-500/30">
              <span className="text-sm font-bold tracking-wider text-purple-300">GAME FEATURES</span>
            </div>
          </div>
          <h2 className="text-5xl md:text-7xl font-black mb-6 gradient-text-epic">
            REVOLUTIONARY GAMEPLAY
          </h2>
          <p className="text-xl text-gray-400 max-w-3xl mx-auto">
            Experience the perfect fusion of AI technology, blockchain innovation, and addictive puzzle gameplay
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <div
              key={index}
              className={`group glass-strong p-8 rounded-2xl border ${feature.borderColor} transition-all duration-500 hover:scale-105 hover:-translate-y-2 animate-fade-in-up`}
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              {/* Icon */}
              <div className={`w-16 h-16 rounded-xl bg-gradient-to-br ${feature.color} p-4 mb-6 group-hover:scale-110 transition-transform duration-300`}>
                <feature.icon className="w-full h-full text-white" />
              </div>

              {/* Title */}
              <h3 className="text-xl font-bold mb-4 text-white group-hover:text-transparent group-hover:bg-gradient-to-r group-hover:bg-clip-text group-hover:from-white group-hover:to-purple-300 transition-all duration-300">
                {feature.title}
              </h3>

              {/* Description */}
              <p className="text-gray-400 text-sm leading-relaxed">
                {feature.description}
              </p>

              {/* Hover Effect Line */}
              <div className={`h-1 w-0 group-hover:w-full bg-gradient-to-r ${feature.color} rounded-full mt-6 transition-all duration-500`}></div>
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="text-center mt-20">
          <div className="glass-strong inline-block px-8 py-4 rounded-xl border border-purple-500/30">
            <p className="text-gray-300">
              <span className="font-bold text-purple-400">100% On-Chain</span> • 
              <span className="font-bold text-blue-400 ml-2">Fully Decentralized</span> • 
              <span className="font-bold text-green-400 ml-2">Provably Fair</span>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
